// NOTE: A frozen copy of the database as it looked at schemaVersion 1, before
// updatedAt and sync_cursors existed. The migration test builds this and then
// lets AppDatabase upgrade it, the same way a user's existing db.sqlite would be upgraded.
// Never edit these, they have to match what's already on people's devices.
const List<String> schemaV1 = [
  '''CREATE TABLE "categories" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "color_hex" TEXT NOT NULL, "icon_key" TEXT NOT NULL, "type" INTEGER NOT NULL, "user_id" TEXT NOT NULL, "is_active" INTEGER NOT NULL DEFAULT 1 CHECK ("is_active" IN (0, 1)), "is_synced" INTEGER NOT NULL DEFAULT 0 CHECK ("is_synced" IN (0, 1)), "is_deleted" INTEGER NOT NULL DEFAULT 0 CHECK ("is_deleted" IN (0, 1)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "templates" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "amount" REAL NOT NULL, "start_date" INTEGER NOT NULL, "billing_day" INTEGER NOT NULL, "type" INTEGER NOT NULL, "user_id" TEXT NOT NULL, "category_id" TEXT NOT NULL REFERENCES categories (id), "is_active" INTEGER NOT NULL DEFAULT 1 CHECK ("is_active" IN (0, 1)), "is_synced" INTEGER NOT NULL DEFAULT 0 CHECK ("is_synced" IN (0, 1)), "is_deleted" INTEGER NOT NULL DEFAULT 0 CHECK ("is_deleted" IN (0, 1)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "transactions" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "amount" REAL NOT NULL, "date" INTEGER NOT NULL, "type" INTEGER NOT NULL, "category_id" TEXT NOT NULL REFERENCES categories (id), "user_id" TEXT NOT NULL, "template_id" TEXT NULL REFERENCES templates (id), "is_synced" INTEGER NOT NULL DEFAULT 0 CHECK ("is_synced" IN (0, 1)), "is_deleted" INTEGER NOT NULL DEFAULT 0 CHECK ("is_deleted" IN (0, 1)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "savings_goals" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "target_amount" REAL NOT NULL, "current_saved_amount" REAL NOT NULL, "user_id" TEXT NOT NULL, "is_active" INTEGER NOT NULL DEFAULT 1 CHECK ("is_active" IN (0, 1)), "is_synced" INTEGER NOT NULL DEFAULT 0 CHECK ("is_synced" IN (0, 1)), "is_deleted" INTEGER NOT NULL DEFAULT 0 CHECK ("is_deleted" IN (0, 1)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "investments" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "amount" REAL NOT NULL, "user_id" TEXT NOT NULL, "is_active" INTEGER NOT NULL DEFAULT 1 CHECK ("is_active" IN (0, 1)), "is_synced" INTEGER NOT NULL DEFAULT 0 CHECK ("is_synced" IN (0, 1)), "is_deleted" INTEGER NOT NULL DEFAULT 0 CHECK ("is_deleted" IN (0, 1)), PRIMARY KEY ("id"))''',
];
